### ISSUE TITLE
websocket directory missing after installing Frankly module using pip

### ISSUE THREAD

**Issue by getsocial-im** [franklyinc/frankly-python#1]
After having installed the module using pip, I couldn't import since the "websocket" directory is missing:

```bash
>>> import frankly
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frankly/__init__.py", line 42, in <module>
    from frankly import ws
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/frankly/ws.py", line 40, in <module>
    from frankly import websocket as ws
ImportError: cannot import name websocket
```

If I compare the directory of the pip installed module with the repository, I can see that "websocket" directory is missing:

```bash
# ls
__init__.py   async.pyc     core.py       errors.pyc    fmp.py        http.pyc      model.py      util.pyc      ws.py
__init__.pyc  auth.py       core.pyc      events.py     fmp.pyc       logger.py     model.pyc     version.py    ws.pyc
async.py      auth.pyc      errors.py     events.pyc    http.py       logger.pyc    util.py       version.pyc
```

**Comment by achille-roussel** [comment]
`frankly.websocket` was missing from setup.py, thanks for reporting!
