### ISSUE TITLE
Auth unit test fails

### ISSUE THREAD

**Issue by getsocial-im** [franklyinc/frankly-python#2]
When running python -m nose in the module's directory, many unit tests fail, more specifically test-06-auth.py, which I planned to use to understand how to generate an identify token:

```bash
======================================================================
ERROR: test_auth_01_anonymous (test-06-auth.TestAuth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pedro/Code/Python/FranklyIntegration/frankly-python/test/test-06-auth.py", line 43, in test_auth_01_anonymous
    auth.identity_token_generator(APP_KEY, APP_SECRET, uid=1, role='anonymous'),
  File "/Users/pedro/Code/Python/FranklyIntegration/frankly-python/frankly/auth.py", line 238, in authenticate
    raise errors.Error('auth', '/auth', response.status_code, response.json(cls=util.JsonDecoder))
Error: error { operation = auth, path = /auth, status = 401, reason = missing identity token in query string }
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): app.franklychat.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /auth/nonce HTTP/1.1" 200 34
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): app.franklychat.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /auth HTTP/1.1" 401 40
--------------------- >> end captured logging << ---------------------
```

I have the environment variables correctly setup (I got them from my app settings in the dashboard). Even with hardcoded values the test fails. Any clue?

**Comment by achille-roussel** [comment]
Could you retry? There was a missing update that didn't get deployed server side, it should be fixed now.

**Comment by getsocial-im** [comment]
It fixed the Auth problem! There are other unit tests failing, but with this fix I can already make good progress. Thanks!
